name: Build and Push nft-pallet

on:
  push:
    branches:
    - master

jobs:
  build-push-template:
    if: ${{ github.repository == 'substrate-developer-hub/substrate-node-nft-pallet' }}
    runs-on: ubuntu-18.04
    steps:
    - name: Trigger playground inclusion
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: paritytech/substrate-playground
        event-type: nft-pallet-updated
        client-payload: '{"id": "node-nft-pallet"}'
